// zoe.c
#define ERROR_NO_COMMAND_GIVEN 1
#define ERROR_NO_STATE_GIVEN 2

// stateio.c
#define ERROR_INVALID_STATE_STRING 3
#define ERROR_PIECE_PARSE 4
#define ERROR_ILLEGAL_PIECE_ON_HIVE 5

// state.c
#define ERROR_ILLEGAL_ACTION 6
